### ISSUE TITLE
Sqrt operation missing?

### ISSUE THREAD

**Issue by joschkaW** [joelpaulson/COBALT#1]
Hi, quick question: In `GreyboxModel.m` in `my_nonlincon` (Line 826), is there a `sqrt` operation missing when adding the variance of g to the mean?

**Comment by joelpaulson** [comment]
Hello, thanks for raising this issue. Yes, I believe there is a missing sqrt in the my_nonlincon definition since the constraint should be mean + tau * std_dev (where std_dev = sqrt(var)) according to equation 37 in the paper. I just adding in the sqrt and pushed the code to main.
